"""Python port of Vercel Chat SDK."""

from chat_sdk.ai import to_ai_messages
from chat_sdk.cards import (
    Actions,
    ActionsElement,
    Button,
    ButtonElement,
    ButtonStyle,
    Card,
    CardChild,
    CardElement,
    CardLink,
    CardText,
    Divider,
    DividerElement,
    Field,
    FieldElement,
    Fields,
    FieldsElement,
    Image,
    ImageElement,
    LinkButton,
    LinkButtonElement,
    LinkElement,
    Section,
    SectionElement,
    Table,
    TableAlignment,
    TableElement,
    Text,
    TextElement,
    TextStyle,
    actions,
    button,
    card,
    card_link,
    card_text,
    card_to_fallback_text,
    divider,
    field,
    fields,
    image,
    is_card_element,
    link_button,
    section,
    table,
    table_element_to_ascii,
    text_element,
)
from chat_sdk.channel import ChannelImpl
from chat_sdk.chat import Chat, OptionsLoadHandler
from chat_sdk.emoji import (
    EmojiResolver,
    convert_emoji_placeholders,
    default_emoji_resolver,
    emoji,
    emoji_to_gchat,
    emoji_to_slack,
    emoji_to_unicode,
    get_emoji,
    resolve_emoji_from_gchat,
    resolve_emoji_from_slack,
)
from chat_sdk.errors import ChatError, ChatNotImplementedError, LockError, RateLimitError, StateNotConnectedError
from chat_sdk.from_full_stream import from_full_stream
from chat_sdk.logger import ConsoleLogger, Logger, LogLevel
from chat_sdk.message_history import MessageHistoryCache, MessageHistoryConfig
from chat_sdk.modals import (
    Modal,
    ModalChild,
    ModalElement,
    RadioSelect,
    RadioSelectElement,
    Select,
    SelectElement,
    SelectOption,
    SelectOptionElement,
    TextInput,
    TextInputElement,
    filter_modal_children,
    is_modal_element,
    modal,
    radio_select,
    select,
    select_option,
    text_input,
)
from chat_sdk.plan import (
    AddTaskOptions,
    CompletePlanOptions,
    Plan,
    PlanContent,
    PlanModel,
    PlanModelTask,
    PlanTask,
    PlanTaskStatus,
    PostableObjectContext,
    StartPlanOptions,
    StreamingPlan,
    StreamingPlanOptions,
    UpdateTaskInput,
    is_postable_object,
    post_postable_object,
)
from chat_sdk.reviver import reviver
from chat_sdk.shared.base_format_converter import BaseFormatConverter
from chat_sdk.shared.errors import (
    AdapterError,
    AdapterPermissionError,
    AdapterRateLimitError,
    AuthenticationError,
    NetworkError,
    ResourceNotFoundError,
    ValidationError,
)
from chat_sdk.shared.streaming_markdown import StreamingMarkdownRenderer
from chat_sdk.state.memory import MemoryStateAdapter
from chat_sdk.thread import ThreadImpl
from chat_sdk.types import (
    ActionEvent,
    Adapter,
    AdapterPostableMessage,
    AppHomeOpenedEvent,
    AssistantContextChangedEvent,
    AssistantThreadStartedEvent,
    Attachment,
    Author,
    BaseAdapter,
    Channel,
    ChannelInfo,
    ChannelVisibility,
    ChatConfig,
    ChatInstance,
    ConcurrencyConfig,
    ConcurrencyStrategy,
    EmojiFormats,
    EmojiValue,
    EphemeralMessage,
    FetchDirection,
    FetchOptions,
    FetchResult,
    FileUpload,
    FormattedContent,
    LinkPreview,
    ListThreadsOptions,
    ListThreadsResult,
    Lock,
    LockScope,
    LockScopeContext,
    MarkdownTextChunk,
    MemberJoinedChannelEvent,
    Message,
    MessageContext,
    MessageData,
    MessageMetadata,
    ModalCloseEvent,
    ModalResponse,
    ModalSubmitEvent,
    OptionsLoadEvent,
    PlanUpdateChunk,
    Postable,
    PostableAst,
    PostableCard,
    PostableMarkdown,
    PostableMessage,
    PostableRaw,
    PostEphemeralOptions,
    QueueEntry,
    RawMessage,
    ReactionEvent,
    ScheduledMessage,
    SentMessage,
    SerializedMessage,
    SlashCommandEvent,
    StateAdapter,
    StreamChunk,
    StreamOptions,
    TaskUpdateChunk,
    Thread,
    ThreadInfo,
    ThreadSummary,
    WebhookOptions,
    WellKnownEmoji,
)

# The upstream Vercel Chat version this release is synced to.
UPSTREAM_PARITY = "4.26.0"

__all__ = [
    "UPSTREAM_PARITY",
    # Core classes
    "Chat",
    "ThreadImpl",
    "ChannelImpl",
    # Plan / PostableObject
    "Plan",
    "PlanTask",
    "PlanTaskStatus",
    "PlanModel",
    "PlanModelTask",
    "PlanContent",
    "StartPlanOptions",
    "AddTaskOptions",
    "UpdateTaskInput",
    "CompletePlanOptions",
    "StreamingPlan",
    "StreamingPlanOptions",
    "PostableObjectContext",
    "is_postable_object",
    "post_postable_object",
    # AI
    "to_ai_messages",
    # Standalone reviver for workflow-safe deserialization
    "reviver",
    # Card builders (PascalCase primary — matches source TS SDK)
    "Actions",
    "Button",
    "Card",
    "CardLink",
    "CardText",
    "Divider",
    "Field",
    "Fields",
    "Image",
    "LinkButton",
    "Section",
    "Table",
    "Text",
    "card_to_fallback_text",
    "table_element_to_ascii",
    # Card builders (snake_case aliases)
    "card",
    "text_element",
    "image",
    "divider",
    "section",
    "actions",
    "button",
    "link_button",
    "field",
    "fields",
    "table",
    "card_link",
    "card_text",
    # Card types
    "ActionsElement",
    "ButtonElement",
    "ButtonStyle",
    "CardChild",
    "CardElement",
    "DividerElement",
    "FieldElement",
    "FieldsElement",
    "ImageElement",
    "LinkButtonElement",
    "LinkElement",
    "SectionElement",
    "TableAlignment",
    "TableElement",
    "TextElement",
    "TextStyle",
    "is_card_element",
    # Emoji
    "EmojiResolver",
    "convert_emoji_placeholders",
    "default_emoji_resolver",
    "emoji",
    "emoji_to_gchat",
    "emoji_to_slack",
    "emoji_to_unicode",
    "get_emoji",
    "resolve_emoji_from_gchat",
    "resolve_emoji_from_slack",
    # Errors
    "ChatError",
    "ChatNotImplementedError",
    "LockError",
    "RateLimitError",
    "StateNotConnectedError",
    # Adapter errors
    "AdapterError",
    "AdapterPermissionError",
    "AdapterRateLimitError",
    "AuthenticationError",
    "NetworkError",
    "ResourceNotFoundError",
    "ValidationError",
    # Format converter
    "BaseFormatConverter",
    # Logger
    "ConsoleLogger",
    "Logger",
    "LogLevel",
    # Message history
    "MessageHistoryCache",
    "MessageHistoryConfig",
    # Modal builders (PascalCase primary — matches source TS SDK)
    "Modal",
    "RadioSelect",
    "Select",
    "SelectOption",
    "TextInput",
    # Modal builders (snake_case aliases)
    "modal",
    "text_input",
    "select",
    "select_option",
    "radio_select",
    # Modal types
    "ModalChild",
    "ModalElement",
    "RadioSelectElement",
    "SelectElement",
    "SelectOptionElement",
    "TextInputElement",
    "filter_modal_children",
    "is_modal_element",
    # State
    "MemoryStateAdapter",
    # Streaming
    "StreamingMarkdownRenderer",
    "from_full_stream",
    # Types
    "ActionEvent",
    "Adapter",
    "AdapterPostableMessage",
    "AppHomeOpenedEvent",
    "AssistantContextChangedEvent",
    "AssistantThreadStartedEvent",
    "Attachment",
    "Author",
    "BaseAdapter",
    "Channel",
    "ChannelInfo",
    "ChannelVisibility",
    "ChatConfig",
    "ChatInstance",
    "ConcurrencyConfig",
    "ConcurrencyStrategy",
    "EmojiFormats",
    "EmojiValue",
    "EphemeralMessage",
    "FetchDirection",
    "FetchOptions",
    "FetchResult",
    "FileUpload",
    "FormattedContent",
    "LinkPreview",
    "ListThreadsOptions",
    "ListThreadsResult",
    "Lock",
    "LockScope",
    "LockScopeContext",
    "MarkdownTextChunk",
    "MemberJoinedChannelEvent",
    "Message",
    "MessageContext",
    "MessageData",
    "MessageMetadata",
    "ModalCloseEvent",
    "ModalResponse",
    "ModalSubmitEvent",
    "OptionsLoadEvent",
    "OptionsLoadHandler",
    "PlanUpdateChunk",
    "Postable",
    "PostableAst",
    "PostableCard",
    "PostableMarkdown",
    "PostableMessage",
    "PostableRaw",
    "PostEphemeralOptions",
    "QueueEntry",
    "RawMessage",
    "ReactionEvent",
    "ScheduledMessage",
    "SentMessage",
    "SerializedMessage",
    "SlashCommandEvent",
    "StateAdapter",
    "StreamChunk",
    "StreamOptions",
    "TaskUpdateChunk",
    "Thread",
    "ThreadInfo",
    "ThreadSummary",
    "WebhookOptions",
    "WellKnownEmoji",
]
